CC=gcc
CFLAGS=
LDFLAGS=
SOURCES=main.c module_info_parser.c
EXECUTABLE=psp2-syslibtrace-nids-extract
all:
	$(CC) $(CFLAGS) $(SOURCES) $(LDFLAGS) -o $(EXECUTABLE)
clean:
	rm -rf $(EXECUTABLE)
